tpu:
  available_ids:
  - jacksisi
  - liucong12601
  - xulijuan
  - wenyangtang
  - liucong126
  - yuanhahah
  - xulin5522
  - cdong121
  - ampere888
  - ohyeah00
  - asdsad0000
  - du55148
  - sollasi
  - sinayliu
  - qqmail4092
  - cheaterchow
  - elong1202
  - cshlhs
  - cq1234
  - tangjudge
  - b201xiaoli
  - zhuangminghui
  - autune
  - yangjiamin
  - zjl001
  - zzr123123
  - smartchaochao
  - denghaimeng
  - zongjiaxin
  - jjjerry12138
  - zhoujiahui0199
  - cycyxcy
  - luanjing
  - ssss7777
  - xuwenhui123
  - jinzhanbo
  - geminiyy
  - zhikaiwang
  - chenhao1213
  - ywhicher
  - qinghui9527
  - chengchi1007
  - yyyyjay
  - quepimao
  - wzywzy1227
  - lemonlaila
  - yccwff
  - asssmer
  - huoqiuxia
  - hysz0821
  - kanwenbin
  - top1pcl
  - yangyangchengcheng
  - ttzyty
  - houwen
  - srmmmm
  - rushly
  - cfy002
  - rqmiraitowa
  - zht121233
  - yinmengmeng
  - dddd110
  - xx03071425
  - uamadeus
  - jufuchao
  - fzzy123
  - keyongkk
  - ycy1n66
  - jokerking1
  - jiangshuai0210
  - xwj66666
  - xiaoluoalice
  - permanentlove
  - rmoope
  - maoshuwen0415
  - eastwangwei
  - jiangshuai0210
  - roseqw
  exhausted_ids:
  - liucong12601
running_notebooks:
- liucong12601/cls-base-rope-d-50
finished_notebooks: []
