task: cls
id: guyuefangyuan6666
pos_type: null
method: colrow
model_size: small
run_id: 2
desc: gpu
is_private: false
dataset_sources: null
kernel_sources: guyuefangyuan6666/cls-small-colrow-gpu-117
resume_full_ckpt: true
resume_source: kernel
resume_infer: false
tpu: false
tpu_workers: 0
tpu_threads: 1
seed: 17
simple:
- resume_bs: true
- total_run_time_hr: 12.0
- train: true
- val: false
