sleep_time_hr: 0
poll_interval_minutes: 10
available_ids:
- cq1234
- tangjudge
- b201xiaoli
- zhuangminghui
- autune
- yangjiamin
- zzr123123
- smartchaochao
- denghaimeng
- zongjiaxin
- jjjerry12138
- zhoujiahui0199
- cycyxcy
- luanjing
- ssss7777
- xuwenhui123
- jinzhanbo
- geminiyy
- zhikaiwang
- chenhao1213
- ywhicher
- qinghui9527
- chengchi1007
- yyyyjay
- quepimao
- wzywzy1227
- lemonlaila
- yccwff
- asssmer
- huoqiuxia
- hysz0821
- kanwenbin
- top1pcl
- yangyangchengcheng
- ttzyty
- houwen
- srmmmm
- rushly
- cfy002
- rqmiraitowa
- zht121233
- yinmengmeng
- dddd110
- xx03071425
- uamadeus
- jufuchao
- fzzy123
- keyongkk
- ycy1n66
- jokerking1
- jiangshuai0210
- xwj66666
- xiaoluoalice
- permanentlove
- rmoope
- maoshuwen0415
- eastwangwei
- jiangshuai0210
- roseqw
- yuanhahah
exhausted_ids:
- liucong12601
- sinayliu
running_nodes:
- id: jacksisi
  left_time: 12
  notebooks:
  - kernel_id: jacksisi/depth-base-none-mres-50
    run_id: 0
    total_runs: 1
    start_time: '2026-01-28 11:46:57'
    resumed_from: null
    history_ids: []
- id: wenyangtang
  left_time: 12
  notebooks: null
- id: cycyxcy
  left_time: 10
  notebooks: []
- id: jjjerry12138
  left_time: 12
  notebooks: []
- id: sinayliu
  left_time: 9.125966971666667
  notebooks: []
- id: zjl001
  left_time: 2.8219920372222216
  notebooks: []
- id: xulijuan
  left_time: 10.86338092611111
  notebooks: []
- id: liucong126
  left_time: 5.12171597111111
  notebooks: null
- id: ampere888
  left_time: 11
  notebooks: null
- id: pycjn666
  left_time: 12
  notebooks: null
- id: xulin5522
  left_time: 20
  notebooks: null
- id: cdong121
  left_time: 10.889214259444444
  notebooks: []
- id: ohyeah00
  left_time: 10.89088092611111
  notebooks: []
- id: asdsad0000
  left_time: 10.892547592777778
  notebooks: []
- id: du55148
  left_time: 10.894492037222221
  notebooks: []
- id: sollasi
  left_time: 20
  notebooks: null
- id: qqmail4092
  left_time: 20
  notebooks: null
- id: cheaterchow
  left_time: 20
  notebooks: []
- id: elong1202
  left_time: 20
  notebooks: []
- id: cshlhs
  left_time: 12.007825370555555
  notebooks: []
finished_notebooks:
- kernel_id: zjl001/cls-base-rope-tpu-53
  total_runs: 1
  start_time: '2026-01-27 22:04:40'
  history_ids: []
- kernel_id: jacksisi/cls-base-abs-tpu-53
  total_runs: 1
  start_time: '2026-01-27 22:06:59'
  history_ids: []
- kernel_id: xulijuan/cls-base-abs-tpu-52
  total_runs: 1
  start_time: '2026-01-27 22:07:09'
  history_ids: []
- kernel_id: wenyangtang/cls-base-abs-tpu-51
  total_runs: 1
  start_time: '2026-01-27 22:07:30'
  history_ids: []
- kernel_id: cdong121/cls-base-none-tpu-53
  total_runs: 1
  start_time: '2026-01-27 22:08:42'
  history_ids: []
- kernel_id: ohyeah00/cls-base-none-tpu-52
  total_runs: 1
  start_time: '2026-01-27 22:08:48'
  history_ids: []
- kernel_id: asdsad0000/cls-base-none-tpu-51
  total_runs: 1
  start_time: '2026-01-27 22:08:54'
  history_ids: []
error_notebooks: null
