task: seg #seg #cls
id: linyunlk243
pos_type: null #relpos alibi null
method: rope #abs none colrow rope
model_size: base #small
suffix: 0
is_private: false
dataset_sources: null
kernel_sources: ly1122/seg-base-rope28
resume_full_ckpt: true
resume_source: kernel #dataset
seed: 28
simple:
  # - batch_size: 64
  # - grad_accum_steps: 1
  - resume_bs: True
  - total_run_time_sec: 40000