available_ids:
- chuasiliu
- cq1234
- cshlhs
- cycyxcy
- denghaimeng
- djiangjiang
- du55148
- dusi605
- elong1202
- fakeid
- fanhuayang
- fzzy123
- geminiyy
- gloden613
- gorgeous0912
- houwen
- huoqiuxia
- hysz0821
- jacksisi
- jcy666
- jiangshuai0210
- jinzhanbo
- jiwei313
- jjjerry12138
- jokerking1
- jufuchao
- kanwenbin
- keyongkk
- kezzymik
- lemonlaila
- linyunlk243
- liucong126
- liucong12601
- luanjing
- ly1122
- maoshuwen0415
- miratowa1
- ohyeah00
- permanentlove
- phoenixcsw01
- pycjn666
- qcx2333
- qinghui9527
- qqmail4092
- quepimao
- rmoope
- roseqw
- rqmiraitowa
- rrrrmm
- rushly
- sh1weiwu
- sinayliu
- smartchaochao
- sollasi
- ssss7777
- starysinger
- tangjiayuan1004
- tangjudge
- tangyujie123
- tianxianglii
- top1pcl
- ttzyty
- uamadeus
- wenyangtang
- wzywzy1227
- xiaoluoalice
- xpeng01
- xulijuan
- xulin5522
- xuwenhui123
- xwj66666
- xx03071425
- yangjiamin
- yccwff
- ycy1n66
- yinmengmeng
- yuanhahah
- ywhicher
- yyyyjay
- zhaotianchi
- zhikaiwang
- zhuangminghui
- zhuxinchen07
- zhuzichen123
- zjl001
- zongjiaxin
- zzr123123
exhausted_ids:
- guyuefangyuan6666
- zhoushuqing
- dingziheng11
- qcrqcrqcr
- ampere888
- asdsad0000
- asssmer
- autune
- cfy002
- b201xiaoli
- cdong121
- cheaterchow
- chencaihonga
- chengchi1007
sleep_time_hr: 0
poll_interval_minutes: 10
running_nodes:
- id: zhangtingfengztf
  notebooks:
  - kernel_id: zhangtingfengztf/cls-small-none-gpu-227
    run_id: 2
    total_runs: 3
    start_time: '2026-02-08 09:24:48'
    resumed_from: ampere888/cls-small-none-gpu-127
    history_ids:
    - ampere888/cls-small-none-gpu-27
  - kernel_id: zhangtingfengztf/cls-small-rope-gpu-226
    run_id: 2
    total_runs: 3
    start_time: '2026-02-08 09:24:59'
    resumed_from: asssmer/cls-small-rope-gpu-126
    history_ids:
    - asssmer/cls-small-rope-gpu-26
  left_time: 30
- id: zhoujiahui0199
  notebooks:
  - kernel_id: zhoujiahui0199/cls-small-none-gpu-226
    run_id: 2
    total_runs: 3
    start_time: '2026-02-08 09:35:37'
    resumed_from: ampere888/cls-small-none-gpu-126
    history_ids:
    - ampere888/cls-small-none-gpu-26
  - kernel_id: zhoujiahui0199/cls-small-abs-gpu-227
    run_id: 2
    total_runs: 3
    start_time: '2026-02-08 09:35:44'
    resumed_from: asdsad0000/cls-small-abs-gpu-127
    history_ids:
    - asdsad0000/cls-small-abs-gpu-27
  left_time: 30
- id: straghtwizard
  notebooks:
  - kernel_id: straghtwizard/cls-small-colrow-gpu-227
    run_id: 2
    total_runs: 3
    start_time: '2026-02-08 09:35:55'
    resumed_from: autune/cls-small-colrow-gpu-127
    history_ids:
    - autune/cls-small-colrow-gpu-27
  - kernel_id: straghtwizard/cls-small-abs-gpu-226
    run_id: 2
    total_runs: 3
    start_time: '2026-02-08 09:46:38'
    resumed_from: asdsad0000/cls-small-abs-gpu-126
    history_ids:
    - asdsad0000/cls-small-abs-gpu-26
  left_time: 30
- id: eastwangwei
  notebooks:
  - kernel_id: eastwangwei/cls-small-rope-gpu-227
    run_id: 2
    total_runs: 3
    start_time: '2026-02-08 09:46:45'
    resumed_from: asssmer/cls-small-rope-gpu-127
    history_ids:
    - asssmer/cls-small-rope-gpu-27
  - kernel_id: eastwangwei/cls-small-colrow-gpu-226
    run_id: 2
    total_runs: 3
    start_time: '2026-02-08 09:46:51'
    resumed_from: autune/cls-small-colrow-gpu-126
    history_ids:
    - autune/cls-small-colrow-gpu-26
  left_time: 30
- id: dddd110
  notebooks:
  - kernel_id: dddd110/cls-small-colrow-ra100-wsfa600-236
    run_id: 2
    total_runs: 3
    start_time: '2026-02-08 09:46:58'
    resumed_from: b201xiaoli/cls-small-colrow-ra100-wsfa600-136
    history_ids:
    - b201xiaoli/cls-small-colrow-ra100-wsfa600-36
  - kernel_id: dddd110/cls-small-colrow-ra400-wsfa600-236
    run_id: 2
    total_runs: 3
    start_time: '2026-02-08 09:47:08'
    resumed_from: cdong121/cls-small-colrow-ra400-wsfa600-136
    history_ids:
    - cdong121/cls-small-colrow-ra400-wsfa600-36
  left_time: 30
- id: sss45633
  notebooks:
  - kernel_id: sss45633/cls-small-colrow-ra500-wsfa600-236
    run_id: 2
    total_runs: 3
    start_time: '2026-02-08 09:47:15'
    resumed_from: cfy002/cls-small-colrow-ra500-wsfa600-136
    history_ids:
    - cfy002/cls-small-colrow-ra500-wsfa600-36
  - kernel_id: sss45633/cls-small-colrow-ra600-wsfa600-236
    run_id: 2
    total_runs: 3
    start_time: '2026-02-08 09:47:20'
    resumed_from: cfy002/cls-small-colrow-ra600-wsfa600-136
    history_ids:
    - cfy002/cls-small-colrow-ra600-wsfa600-36
  left_time: 30
- id: robinrainy
  notebooks:
  - kernel_id: robinrainy/cls-small-colrow-ra300-wsfa200-236
    run_id: 2
    total_runs: 3
    start_time: '2026-02-08 09:47:29'
    resumed_from: cheaterchow/cls-small-colrow-ra300-wsfa200-136
    history_ids:
    - cheaterchow/cls-small-colrow-ra300-wsfa200-36
  - kernel_id: robinrainy/cls-small-colrow-ra300-wsfa500-236
    run_id: 2
    total_runs: 3
    start_time: '2026-02-08 09:47:39'
    resumed_from: chencaihonga/cls-small-colrow-ra300-wsfa500-136
    history_ids:
    - chencaihonga/cls-small-colrow-ra300-wsfa500-36
  left_time: 30
- id: hsdfuieqg
  notebooks:
  - kernel_id: hsdfuieqg/cls-small-colrow-ra300-wsfa800-236
    run_id: 2
    total_runs: 3
    start_time: '2026-02-08 09:47:46'
    resumed_from: chengchi1007/cls-small-colrow-ra300-wsfa800-136
    history_ids:
    - chengchi1007/cls-small-colrow-ra300-wsfa800-36
  - kernel_id: hsdfuieqg/cls-small-colrow-ra200-wsfa600-236
    run_id: 2
    total_runs: 3
    start_time: '2026-02-08 09:58:08'
    resumed_from: b201xiaoli/cls-small-colrow-ra200-wsfa600-136
    history_ids:
    - b201xiaoli/cls-small-colrow-ra200-wsfa600-36
  left_time: 30
- id: yangyangchengcheng
  notebooks:
  - kernel_id: yangyangchengcheng/cls-small-colrow-ra300-wsfa600-236
    run_id: 2
    total_runs: 3
    start_time: '2026-02-08 09:58:15'
    resumed_from: cdong121/cls-small-colrow-ra300-wsfa600-136
    history_ids:
    - cdong121/cls-small-colrow-ra300-wsfa600-36
  - kernel_id: yangyangchengcheng/cls-small-colrow-ra300-wsfa100-236
    run_id: 2
    total_runs: 3
    start_time: '2026-02-08 09:58:21'
    resumed_from: cheaterchow/cls-small-colrow-ra300-wsfa100-136
    history_ids:
    - cheaterchow/cls-small-colrow-ra300-wsfa100-36
  left_time: 30
- id: srmmmm
  notebooks:
  - kernel_id: srmmmm/cls-small-colrow-ra300-wsfa300-236
    run_id: 2
    total_runs: 3
    start_time: '2026-02-08 09:58:28'
    resumed_from: chencaihonga/cls-small-colrow-ra300-wsfa300-136
    history_ids:
    - chencaihonga/cls-small-colrow-ra300-wsfa300-36
  - kernel_id: srmmmm/cls-small-colrow-ra300-wsfa800-237
    run_id: 2
    total_runs: 3
    start_time: '2026-02-08 09:58:35'
    resumed_from: chengchi1007/cls-small-colrow-ra300-wsfa800-137
    history_ids:
    - chengchi1007/cls-small-colrow-ra300-wsfa800-37
  left_time: 30
- id: chenhao1213
  left_time: 30
  notebooks:
- id: chenrunze11
  left_time: 30
  notebooks:
finished_notebooks: []
