task: cls
id: 
pos_type: alibi # alibi relpos
method: none # colrow, rope, abs, none, patch
model_size: base
run_id: 0
# total_runs: 1
desc: gpu
# desc_keys: ["rc_alpha", "warmup_steps_for_aux"]
is_private: false
dataset_sources: null
kernel_sources: null
resume_full_ckpt: false
resume_source: kernel
resume_infer: false
tpu: false
tpu_workers: 0
tpu_threads: 1
seed: 16
simple:
- resume_bs: true
- total_run_time_hr: 12.0
# - rc_alpha: 70
# - warmup_steps_for_aux: 300
