task: cls
id: zjl001
pos_type: null
method: none
model_size: base
suffix: 0
desc: lr3e-5
is_private: false
dataset_sources: null
kernel_sources: null
resume_full_ckpt: false
resume_source: kernel
resume_infer: false
tpu: true
tpu_workers: 0
tpu_threads: 1
seed: 50
simple:
- resume_bs: true
- total_run_time_hr: 12.0
- lr: 3.0e-5
