task: depth
id: 
pos_type: null # alibi relpos
method: colrow # colrow, rope, abs, none, patch
model_size: base
run_id: 0
desc: mres
desc_keys: ["rc_alpha", "warmup_steps_for_aux"]
is_private: false
dataset_sources: null
kernel_sources: null
resume_full_ckpt: false
resume_source: kernel
resume_infer: false
tpu: false
tpu_workers: 0
tpu_threads: 1
seed: 16
simple:
- resume_bs: true
- total_run_time_hr: 12.0
- rc_alpha: 600
- warmup_steps_for_aux: 600
