task: depth
id: robinrainy
pos_type: null # alibi relpos
method: none # colrow, rope, abs, none
model_size: small
run_id: 0
desc: tpu8c
# desc_keys: ["img_sizes"]
is_private: false
dataset_sources: null
kernel_sources: null
resume_full_ckpt: false
resume_source: kernel
resume_infer: false
tpu: true
tpu_workers: 0
tpu_threads: 1
seed: 50
simple:
- resume_bs: true
- total_run_time_hr: 9.0
- train: true
- val: true
# - rc_alpha: 300
# - img_sizes: [224, 192, 288]
# - show_peak_gpu_mem: True
# - val: false
# - batch_size: 16
# - lr: 5.0e-05
