task: depth
id: 
pos_type: null # alibi relpos
method: abs # colrow, rope, abs, none
model_size: base
run_id: 0
desc: tpu
# desc_keys: ["align_mode"]
desc_keys: ["lr"]
is_private: false
dataset_sources: null
kernel_sources: null
resume_full_ckpt: false
resume_source: kernel
resume_infer: false
tpu: true
tpu_workers: 0
tpu_threads: 1
seed: 16
simple:
- resume_bs: true
- total_run_time_hr: 9.0
- train: true
# - val: false
- break_at_epoch: 5
- silog_w: 0.0
- l1_w: 1.0
- grad_w: 0.0
- align_mode: "mean_std"  # "scale", "scale_shift", or "mean_std"
- mean_std_variant: "zscore_both"  # "affine" or "zscore_both"
# - rc_alpha: 70
- lr: 7.0e-5
# - weight_decay: 0.05
# - warmup_steps_for_aux: 60
# - rc_alpha: 300
# - img_sizes: [224, 192, 288]
# - show_peak_gpu_mem: True
# - val: false
# - batch_size: 16
