task: depth
id: jjjerry12138  
pos_type: null # alibi relpos
method: rope # colrow, rope, abs, none
model_size: base
run_id: 0
desc: bs48lr1e-4
is_private: false
dataset_sources: null
kernel_sources: null
resume_full_ckpt: false
resume_source: kernel
resume_infer: false
tpu: true
tpu_workers: 0
tpu_threads: 1
seed: 50
simple:
- resume_bs: true
- total_run_time_hr: 1.0
- batch_size: 48
- lr: 1.0e-04
